# Generated by Django 4.2.8 on 2023-12-29 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='BookPrice',
            field=models.IntegerField(default=0),
        ),
    ]
